development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: contacts-rb-development
  pool: 5
  password:

test: &test
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: contacts-rb-test
  pool: 5

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
