# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e5f94d392818276f3468fb0298022167ea8c3a2d743d1942fc5f63fa5555510b1ca693ba69ac6c3a8306a81d4af90096291163805c121e70baa19272cc5776d

test:
  secret_key_base: 487b91367e972cfc2846410d01b2447fa43870997da0ad4b0a424ed4a3f646aef5472bd6a682cc7c99ab8b731acd03258d548fc98bc5b246bf2bc376941313c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
